format = """
$directory$git_branch$git_commit$git_state$git_status$git_metrics$ruby$go
$character
"""

right_format = "$kubernetes"

[directory]
truncation_length = 5
truncate_to_repo = false
truncation_symbol = "…/"
style = "white"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
style = "purple"

[git_metrics]
disabled = false
added_style = "green"
deleted_style = "red"

[ruby]
format = "[$symbol($version )]($style) "
style = "red"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '
style = "cyan"
